### ISSUE TITLE
crash on Ubuntu 14.04

### ISSUE THREAD

**Issue by zzqcn** [Leviathan1995/regex#1]
Whatever the regex experssion is, the Lregex will crash.

- OS: Ubuntu 14.04 Server 64bit
- Compiler: g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
- output:

```
$ ./Lregex 
First step:please input regex expression:
ab

Regex expression:
a.b
String length3

Third step:transform RegexPost
ab.
String length:3

Fourth step:get char list
a b 
char numbers: 2


------------------------
Segmentation fault (core dumped)
```

**Comment by Leviathan1995** [comment]
这是我大一写的代码，现在看来，很多地方都不规范，内存泄漏严重，你要有兴趣可以fork过去自己修改，我的只支持简单的正则运算，你可以添加扩展。
参考：http://www.rainbowcoder.link/%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F.html

**Comment by zzqcn** [comment]
好的，我在NFA转DFA时有点困难，所以来参考你的代码了

**Comment by Leviathan1995** [comment]
按照子集构造法来，实现过程需要完成一个表的填写，按照表的内容进行转换。编译原理的书上有

**Comment by zzqcn** [comment]
好的，我都没学过编译原理（通信专业），之前参考的是Russ Cox的文章 https://swtch.com/~rsc/regexp/ 。只实现了带ε边的NFA。目的是实现一个多模的正则匹配引擎，就像intel的hyperscan那样。

谢谢你指点，我会阅读一下你说的这些书和文章的。

**Comment by Leviathan1995** [comment]
不客气。
